[package]
name = "engine-trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
rand = "0.8.5"
serde = "1.0.190"
shakmaty = "0.26.0"
